### ISSUE TITLE
Very high virtual memory consumption

### ISSUE THREAD

**Issue by FireyFly** [jmesmon/illum#11]
I recently started using illum, and just noticed something curious: while some processes res a coerve quite a lot of memory (maybe a few GB at most), illum's daemon seems to be in a separate tier with htop listing its virtual memory as 20.0T (!). Specifically it's `illum-d` reserving this amount of memory.

Not sure if this is in any way related to the rest of my system/setup, but it's a relatively vanilla NixOS setup (seeing as I started using NixOS two weeks ago, and setup this laptop yesterday). The system in question has an uptime of 16h, of which maybe 11h was during suspension (suspend-to-RAM).

**Comment by codyps** [comment]
This is (very) likely caused by the default use of `-fsanitize=address` in the build script.

If you'd like, you can disable sanitization by setting the env var `SANITIZE_FLAGS` to an empty string, which will cut virtual memory usage.

https://github.com/jmesmon/illum/blob/10f59d53eb6155348da72f5a11ae8609bb7fd377/config.sh#L83

**Comment by ghost** [comment]
ASAN is a debugging tool and not intended to be left on in production. Would suggest this is removed from the default options.

**Comment by codyps** [comment]
When performing packaging, all one needs to do is provide their own `CFLAGS` and the santizers (as well as the custom optimization and debugging flags) are disabled. This happens by default in arch-linux's `makepkg` (ie: nothing special is done in the pkgbuild, it just always has `CFLAGS` exported).

Other systems should probably behave similarly. If you're not compiling illum via the use of packaging, you'll need to disable it. `CFLAGS="-O2" ./build` will probably work fine.

As an oversight, the rpm generation did not include the appropriate `%set_build_flags` macro to do this. I'll be adding that shortly.
