### ISSUE TITLE
failed to initialize sys backlight at '/sys/class/backlight/intel_backlight' (-1)

### ISSUE THREAD

**Issue by AladW** [jmesmon/illum#2]
When trying to run illum-d, I get the following error:
```
failed to initialize sys backlight at '/sys/class/backlight/intel_backlight' (-1)
```
strace: https://paste.xinu.at/kbnr/
stat /sys/class/backlight/intel_backlight: https://paste.xinu.at/PgcpWe/
file contents: https://paste.xinu.at/mjCKiT/
uname:
```
Linux thinkpad 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux
```

**Comment by codyps** [comment]
Based on the strace, it looks like illum-d is opening max_brightness without issue, and reading data from it, but then deciding it has failed to initialize.

I've pushed a new commit that may fix the issue, please let me know if it works for you.

**Comment by AladW** [comment]
Thanks, works fine now.
