### ISSUE TITLE
The license should be explicitly stated

### ISSUE THREAD

**Issue by dancek** [jmesmon/illum#4]
Illum seems to be licensed under AGPLv3, which is mentioned at least in `illum.spec` and the Arch Linux package. This is not immediately obvious.

The license should be stated in at least some of the following ways.

- [ ] a mention in `README`
- [ ] a file called `COPYING` with the [fulltext](https://www.gnu.org/licenses/agpl.txt)
- [ ] copyright notice and a statement of copying permission in each source file

> Whichever license you plan to use, the process involves adding two elements to each source file of your program: a copyright notice (such as “Copyright 1999 Terry Jones”), and a statement of copying permission, saying that the program is distributed under the terms of the GNU General Public License (or the Lesser GPL).

See https://www.gnu.org/licenses/gpl-howto.html

**Comment by dancek** [comment]
For me, just a mention in `README` would be enough for practical purposes. This is probably bad legal advice, though.

**Comment by codyps** [comment]
You're right, I should really put that somewhere other than the pkgbuild (which isn't even in this repo) and the rpm spec (which for practical purposes I don't use). I've added a readme entry
