### ISSUE TITLE
ninja: error: 'ccan/ccan/pr_log/pr_log.c', needed by '.build-illum-d/ccan/ccan/pr_log/pr_log.c.o', missing

### ISSUE THREAD

**Issue by hramrach** [jmesmon/illum#5]
+ ./build
ninja: error: 'ccan/ccan/pr_log/pr_log.c', needed by '.build-illum-d/ccan/ccan/pr_log/pr_log.c.o', missing and no known rule to make it

**Comment by codyps** [comment]
`git submodule update --init`

**Comment by hramrach** [comment]
that's not what the build instructions say.

Also if you download the snapshot as specified in the spec file it does not contain the submodule

**Comment by codyps** [comment]
You're right, the spec file doesn't work. I never needed this on an rpm based distro, so I hadn't worried about fixing it. I'm primarily using it on arch: https://aur.archlinux.org/packages/illum-git/ . That'd be a fair issue to open.

As for the build instructions, they currently presume all source code has been fetched. They aren't source code fetching instructions. Those could be added, if desired.
