### ISSUE TITLE
`illum.spec` does not work

### ISSUE THREAD

**Issue by codyps** [jmesmon/illum#6]
- [x] fetching is wrong
- [x] automate updating the commit hash

(and probably a few other things).

For me, this is a low priority, but I'd be happy to accept patches to the spec if desired (or remove it if it is better maintained elsewhere).

cc @hramrach

**Comment by hramrach** [comment]
for updating the spec you probably want a .spec.in file and do-rpm creating .spec by replacing hash placeholders.

**Comment by codyps** [comment]
Yep, that methodology makes sense.
