### ISSUE TITLE
-fsanitize=address is not widely supported

### ISSUE THREAD

**Issue by hramrach** [jmesmon/illum#8]
People running 'stable' distribution on non-x86 will not be able to build illum out of the box.

openSUSE 42.2 with gcc 4.8.5 does not manage.

This can be detected by gcc failing to build/link when option passed: 

[   40s] [25/26] cc -fsanitize=address  -ggdb3 -fvar-tracking-assignments  -flto  -Og -ggdb3 -fvar-tracking-assignments  -o illum-ctl .build-illum-ctl/main-ctl.c.o -lev -levdev 
[   40s] FAILED: cc -fsanitize=address  -ggdb3 -fvar-tracking-assignments  -flto  -Og -ggdb3 -fvar-tracking-assignments  -o illum-ctl .build-illum-ctl/main-ctl.c.o -lev -levdev 
[   40s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/4.8/../../../../armv7hl-suse-linux-gnueabi/bin/ld: cannot find libasan_preinit.o: No such file or directory
[   40s] /usr/lib/gcc/armv7hl-suse-linux-gnueabi/4.8/../../../../armv7hl-suse-linux-gnueabi/bin/ld: cannot find -lasan
[   40s] collect2: error: ld returned 1 exit status
[   40s] ccan/ccan/pr_log/pr_log.c:1:0: warning: -fsanitize=address not supported for this target [enabled by default]
[   40s]  /* Licensed under LGPLv2.1+ - see LICENSE file for details */
[   40s]  ^
[   41s] main-daemon.c:1:0: warning: -fsanitize=address not supported for this target [enabled by default]
[   41s]  /* ex: set noet sw=8 sts=8 ts=8 tw=78: */
[   41s]  ^
[   41s] ninja: build stopped: subcommand failed.

**Comment by codyps** [comment]
`config.sh` is supposed to avoid using those when the compiler doesn't like them. Likely means something in the "see if this flag works" logic (`cflag_x()`) needs a bit of work. Perhaps it needs to try to link? (seems like that is where the failure is occurring here).

**Comment by hramrach** [comment]
yes, it needs to try to link.
